name: CloudStream Derleyici

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  CloudStreamDerleyici:
    runs-on: ubuntu-latest
    steps:
      - name: "'src' Depo Kontrolü"
        uses: actions/checkout@v4
        with:
          path: "src"

      - name: "'build' Depo Kontrolü"
        uses: actions/checkout@v4
        with:
          ref: "builds"
          path: "builds"

      - name: Eski Derlemeleri Temizle
        run: rm -f $GITHUB_WORKSPACE/builds/*.cs3 || true

      - name: JDK 17 Ayarla
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Android SDK Ortamını Ayarla
        run: |
          echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=/usr/local/lib/android/sdk" >> $GITHUB_ENV

      - name: Eklentileri Derle
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds 2>/dev/null || true
          cp build/plugins.json $GITHUB_WORKSPACE/builds 2>/dev/null || cp plugins.json $GITHUB_WORKSPACE/builds 2>/dev/null || true

      - name: Derlemeleri Yükle
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Build: $(date +'%Y-%m-%d %H:%M:%S UTC') [skip ci]" || exit 0
          git push